### ISSUE TITLE
KeyError: 'landsat_collection' [Re-Training the Classifier]

### ISSUE THREAD

**Issue by jimpaulobautista** [kvos/CoastSat#403]
![image](https://user-images.githubusercontent.com/108282093/235612431-6e676aaa-41fe-4377-a7a8-1101fad74587.png)

I am attempting to re-train the CoastSat by familiarizing the classifier on the coasts of our country. I keep on getting this error when downloading the images. I also tried this on the train_new_classifier example but I got the same error. I suspect that there's an error with the SDS_download file.

`# dowload images at the sites

dates = ['2019-01-01', '2019-07-01']

sat_list = ['L8']

for site in train_sites:
    polygon = SDS_tools.polygon_from_kml(os.path.join(filepath_sites,site))
    polygon = SDS_tools.smallest_rectangle(polygon)
    sitename = site[:site.find('.')]  
    inputs = {'polygon':polygon, 'dates':dates, 'sat_list':sat_list,
             'sitename':sitename, 'filepath':filepath_images}
    print(sitename)
    metadata = SDS_download.retrieve_images(inputs)`

**Comment by kvos** [comment]
oh yeah, I know what that error is. Just add another field 'landsat_collection':'C02' in the input dictionary and it should be good to go.

**Comment by jimpaulobautista** [comment]
This works, thanks  @kvos  for the swift response! Also, I initially used Google Earth Pro in plotting the .kml polygons and I keep on getting linearring error. Apparently, CoastSat strictly prefers to process the polygons generated in Google My Maps.

**Comment by jimpaulobautista** [comment]
Hi Kilian, I got the same landsat_collection error again in SDS_classify, even after adding 'landsat_collection':'C02' field in the input dictionary. What seems to be the problem? Tried different approaches but still no progress. Thanks.
![image](https://user-images.githubusercontent.com/108282093/235851604-459f51a0-20d0-4b1b-9fee-995cb03d6253.png)


Here's the copy of the code I used.
`dates = ['2019-01-01', '2019-07-01']
sat_list = ['L8']
for site in train_sites:
    polygon = SDS_tools.polygon_from_kml(os.path.join(filepath_sites,site))
    polygon = SDS_tools.smallest_rectangle(polygon)
    sitename = site[:site.find('.')]  
    inputs = {'polygon':polygon, 'dates':dates, 'sat_list':sat_list,
             'sitename':sitename, 'filepath':filepath_images,  'landsat_collection': 'C02'}
    print(sitename)
    #metadata = SDS_download.retrieve_images(inputs)
    metadata = SDS_download.get_metadata(inputs);`

`# label images
%matplotlib qt
for site in train_sites:
    settings['inputs']['sitename'] = site[:site.find('.')]
# load metadata
    metadata = SDS_download.get_metadata(settings['inputs'])
# annotate images
    SDS_classify.label_images(metadata,settings)`

**Comment by pdmini** [comment]
Hi jimpaulobautista please try like below :
# settings
settings ={'filepath_train':filepath_train, # folder where the labelled images will be stored
           'cloud_thresh':0.9, # percentage of cloudy pixels accepted on the image
           'cloud_mask_issue':True, # set to True if problems with the default cloud mask 
           'pan_off': True, # True to switch pansharpening off for Landsat 7/8/9 imagery
           'inputs':{'filepath':filepath_images,'landsat_collection': 'C02','collection':'C02'}, # folder where the images are stored
           'labels':{'sand':1,'white-water':2,'water':3,'other land features':4}, # labels for the classifier
           'colors':{'sand':[1, 0.65, 0],'white-water':[1,0,1],'water':[0.1,0.1,0.7],'other land features':[0.8,0.8,0.1]},
           'tolerance':0.01, # this is the pixel intensity tolerance, when using flood fill for sandy pixels
                             # set to 0 to select one pixel at a time
            }

in the initial settings the classifier works

**Comment by jimpaulobautista** [comment]
Woah, this works! Thank you so much @pdmini 💯

**Comment by jimpaulobautista** [comment]
@pdmini I am stuck on dividing the training data into 70% train and 30% evaluate. I have encountered a Value Error (Input X contains infinity or a value too large for dtype('float64'). Did you encounter this error too? If yes, may I ask on how you fixed this?

Thank you!

![image](https://github.com/kvos/CoastSat/assets/108282093/0526857e-8c65-48d3-b268-9f7fa7021764)
![image](https://github.com/kvos/CoastSat/assets/108282093/8a3135a7-da89-4e76-b863-9a15c3197b72)
![image](https://github.com/kvos/CoastSat/assets/108282093/21170efb-94a0-4ec7-b5c6-2eb371d25151)
![image](https://github.com/kvos/CoastSat/assets/108282093/782c8612-1797-44bc-a764-b319445d7871)
![image](https://github.com/kvos/CoastSat/assets/108282093/32d554cd-b8f1-4a4c-9f14-1fb9780bbab9)
![image](https://github.com/kvos/CoastSat/assets/108282093/dd22a2bc-ae4f-4385-b433-39ec0c2c86ec)

**Comment by kvos** [comment]
this keyerror issue has been fixed in the latest commit

**Comment by jimpaulobautista** [comment]
How about the ValueError? @kvos  I scanned on the previous reports, it is probably connected to the presence of nan and inf values on the X array but I still can't figure out how to fix it. Thanks!

**Comment by jimpaulobautista** [comment]
UPDATE: I added `X[np.isinf(X)] = 1e-9` in SDS_classify.py after the **line 455**. 
![image](https://github.com/kvos/CoastSat/assets/108282093/75da5ba7-43d1-4a41-9761-a67b6ba84b4a)

I ran the code and I got this accuracy value. Can you please verify if this is correct? @kvos 

Thanks again. 
![image](https://github.com/kvos/CoastSat/assets/108282093/e560033f-e2bf-4ee4-b4f4-b8b7e258fd2d)
